// ARTICULOS
export const OBTENER_ARTICULOS = 'OBTENER_RECURSOS'
export const EDITAR_ARTICULO = 'OBTENER_RECURSOS'
export const ELIMINAR_ARTICULO = 'OBTENER_RECURSOS'

// RECURSOS

export const OBTENER_RECURSOS = 'OBTENER_RECURSOS'
export const RECURSOS_CATEGORIA = 'RECURSOS_CATEGORIA'
export const CATEGORIA_ACTUAL = 'CATEGORIA_ACTUAL'

//AUTENTICACION

